### ISSUE TITLE
DotPosition, leading or trailing?

### ISSUE THREAD

**Issue by radavis** [LaunchAcademy/launchcop#3]
Currently, the enforced style is trailing. Examples of both:

## Leading
```
flash[:alert] = @answer_submission
  .errors
  .messages
  .values
  .flatten
  .join(' ')
```

## Trailing
```
flash[:alert] = @answer_submission.
  errors.
  messages.
  values.
  flatten.
  join(' ')
```
```

**Comment by dpickett** [comment]
I've always been a fan of trailing. I've found it makes specs easier to read as trailing dots indicate that the assertion spans down to the next line

**Comment by radavis** [comment]
I'm down with that.
